
/**
 * Generated by Babylon.js Editor
 */

import { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets } from "babylonjs-editor-tools";
import * as scripts_box from "./scripts/box";
import * as scripts_ControlManager from "./scripts/ControlManager";
import * as scripts_DownloadManager from "./scripts/DownloadManager";

export const scriptsMap = {
    "scripts/box.ts": scripts_box,
	"scripts/ControlManager.ts": scripts_ControlManager,
	"scripts/DownloadManager.ts": scripts_DownloadManager
};

export { loadScene, scriptsDictionary, scriptAssetsCache, _applyScriptsForObject, _removeRegisteredScriptInstance, _preloadScriptsAssets };
